# Generated by Django 4.2.3 on 2023-07-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_course_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='3 months', max_length=500),
        ),
    ]
